import { TerraformConfig, TerraformResource } from "@tfkonf/core";

export interface AwsMedialiveChannelArgsCdiInputSpecification {
  resolution: string;
}

export interface AwsMedialiveChannelArgsDestinationsMediaPackageSettings {
  channel_id: string;
}

export interface AwsMedialiveChannelArgsDestinationsMultiplexSettings {
  multiplex_id: string;
  program_name: string;
}

export interface AwsMedialiveChannelArgsDestinationsSettings {
  password_param?: string;
  stream_name?: string;
  url?: string;
  username?: string;
}

export interface AwsMedialiveChannelArgsDestinations {
  id: string;
  media_package_settings?: AwsMedialiveChannelArgsDestinationsMediaPackageSettings[];
  multiplex_settings?: AwsMedialiveChannelArgsDestinationsMultiplexSettings;
  settings?: AwsMedialiveChannelArgsDestinationsSettings[];
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioNormalizationSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioWatermarkSettingsNielsenWatermarksSettingsNielsenCbetSettings {
  cbet_check_digit_string: string;
  cbet_stepaside: string;
  csid: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioWatermarkSettingsNielsenWatermarksSettingsNielsenNaesIiNwSettings {
  check_digit_string: string;
  sid: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioWatermarkSettingsNielsenWatermarksSettings {
  nielsen_cbet_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioWatermarkSettingsNielsenWatermarksSettingsNielsenCbetSettings;
  nielsen_naes_ii_nw_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioWatermarkSettingsNielsenWatermarksSettingsNielsenNaesIiNwSettings[];
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioWatermarkSettings {
  nielsen_watermarks_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioWatermarkSettingsNielsenWatermarksSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsAacSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsAc3Settings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsEac3AtmosSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsEac3Settings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsMp2Settings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsPassThroughSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsWavSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettings {
  aac_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsAacSettings;
  ac3_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsAc3Settings;
  eac3_atmos_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsEac3AtmosSettings;
  eac3_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsEac3Settings;
  mp2_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsMp2Settings;
  pass_through_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsPassThroughSettings;
  wav_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettingsWavSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsRemixSettingsChannelMappingsInputChannelLevels {
  gain: number;
  input_channel: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsRemixSettingsChannelMappings {
  output_channel: number;
  input_channel_levels: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsRemixSettingsChannelMappingsInputChannelLevels[];
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsRemixSettings {
  channel_mappings: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsRemixSettingsChannelMappings[];
}

export interface AwsMedialiveChannelArgsEncoderSettingsAudioDescriptions {
  audio_selector_name: string;
  name: string;
  audio_normalization_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioNormalizationSettings;
  audio_watermark_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsAudioWatermarkSettings;
  codec_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsCodecSettings;
  remix_settings?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptionsRemixSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsAvailBlankingAvailBlankingImage {
  uri: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsAvailBlanking {
  avail_blanking_image?: AwsMedialiveChannelArgsEncoderSettingsAvailBlankingAvailBlankingImage;
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsAribDestinationSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsBurnInDestinationSettingsFont {
  uri: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsBurnInDestinationSettings {
  alignment?: string;
  background_color?: string;
  background_opacity?: number;
  font_color?: string;
  font_opacity?: number;
  font_resolution?: number;
  font_size?: string;
  outline_color: string;
  outline_size?: number;
  shadow_color?: string;
  shadow_opacity?: number;
  shadow_x_offset?: number;
  shadow_y_offset?: number;
  teletext_grid_control: string;
  x_position?: number;
  y_position?: number;
  font?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsBurnInDestinationSettingsFont;
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsDvbSubDestinationSettingsFont {
  uri: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsDvbSubDestinationSettings {
  alignment?: string;
  background_color?: string;
  background_opacity?: number;
  font_color?: string;
  font_opacity?: number;
  font_resolution?: number;
  outline_color?: string;
  outline_size?: number;
  shadow_color?: string;
  shadow_opacity?: number;
  shadow_x_offset?: number;
  shadow_y_offset?: number;
  teletext_grid_control?: string;
  x_position?: number;
  y_position?: number;
  font?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsDvbSubDestinationSettingsFont;
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsEbuTtDDestinationSettings {
  copyright_holder?: string;
  fill_line_gap?: string;
  font_family?: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsEmbeddedDestinationSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsEmbeddedPlusScte20DestinationSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsRtmpCaptionInfoDestinationSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsScte20PlusEmbeddedDestinationSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsScte27DestinationSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsSmpteTtDestinationSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsTeletextDestinationSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsTtmlDestinationSettings {
  style_control: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsWebvttDestinationSettings {
  style_control: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettings {
  arib_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsAribDestinationSettings;
  burn_in_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsBurnInDestinationSettings;
  dvb_sub_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsDvbSubDestinationSettings;
  ebu_tt_d_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsEbuTtDDestinationSettings;
  embedded_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsEmbeddedDestinationSettings;
  embedded_plus_scte20_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsEmbeddedPlusScte20DestinationSettings;
  rtmp_caption_info_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsRtmpCaptionInfoDestinationSettings;
  scte20_plus_embedded_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsScte20PlusEmbeddedDestinationSettings;
  scte27_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsScte27DestinationSettings;
  smpte_tt_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsSmpteTtDestinationSettings;
  teletext_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsTeletextDestinationSettings;
  ttml_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsTtmlDestinationSettings;
  webvtt_destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettingsWebvttDestinationSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptions {
  accessibility?: string;
  caption_selector_name: string;
  language_code?: string;
  language_description?: string;
  name: string;
  destination_settings?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptionsDestinationSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsGlobalConfigurationInputLossBehaviorInputLossImageSlate {
  uri: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsGlobalConfigurationInputLossBehavior {
  black_frame_msec?: number;
  input_loss_image_color?: string;
  input_loss_image_type?: string;
  repeat_frame_msec?: number;
  input_loss_image_slate?: AwsMedialiveChannelArgsEncoderSettingsGlobalConfigurationInputLossBehaviorInputLossImageSlate;
}

export interface AwsMedialiveChannelArgsEncoderSettingsGlobalConfiguration {
  initial_audio_gain?: number;
  input_end_action?: string;
  output_locking_mode?: string;
  output_timing_source?: string;
  support_low_framerate_inputs?: string;
  input_loss_behavior?: AwsMedialiveChannelArgsEncoderSettingsGlobalConfigurationInputLossBehavior;
}

export interface AwsMedialiveChannelArgsEncoderSettingsMotionGraphicsConfigurationMotionGraphicsSettingsHtmlMotionGraphicsSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsMotionGraphicsConfigurationMotionGraphicsSettings {
  html_motion_graphics_settings?: AwsMedialiveChannelArgsEncoderSettingsMotionGraphicsConfigurationMotionGraphicsSettingsHtmlMotionGraphicsSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsMotionGraphicsConfiguration {
  motion_graphics_insertion?: string;
  motion_graphics_settings: AwsMedialiveChannelArgsEncoderSettingsMotionGraphicsConfigurationMotionGraphicsSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsNielsenConfiguration {
  distributor_id?: string;
  nielsen_pcm_to_id3_tagging?: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsArchiveGroupSettingsArchiveCdnSettingsArchiveS3Settings {
  canned_acl?: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsArchiveGroupSettingsArchiveCdnSettings {
  archive_s3_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsArchiveGroupSettingsArchiveCdnSettingsArchiveS3Settings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsArchiveGroupSettingsDestination {
  destination_ref_id: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsArchiveGroupSettings {
  rollover_interval?: number;
  archive_cdn_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsArchiveGroupSettingsArchiveCdnSettings;
  destination: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsArchiveGroupSettingsDestination;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsFrameCaptureGroupSettingsDestination {
  destination_ref_id: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsFrameCaptureGroupSettingsFrameCaptureCdnSettingsFrameCaptureS3Settings {
  canned_acl?: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsFrameCaptureGroupSettingsFrameCaptureCdnSettings {
  frame_capture_s3_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsFrameCaptureGroupSettingsFrameCaptureCdnSettingsFrameCaptureS3Settings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsFrameCaptureGroupSettings {
  destination: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsFrameCaptureGroupSettingsDestination;
  frame_capture_cdn_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsFrameCaptureGroupSettingsFrameCaptureCdnSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsCaptionLanguageMappings {
  caption_channel: number;
  language_code: string;
  language_description: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsDestination {
  destination_ref_id: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsAkamaiSettings {
  connection_retry_interval?: number;
  filecache_duration?: number;
  num_retries?: number;
  restart_delay?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsBasicPutSettings {
  connection_retry_interval?: number;
  filecache_duration?: number;
  num_retries?: number;
  restart_delay?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsMediaStoreSettings {
  connection_retry_interval?: number;
  filecache_duration?: number;
  num_retries?: number;
  restart_delay?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsS3Settings {
  canned_acl?: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsWebdavSettings {
  connection_retry_interval?: number;
  filecache_duration?: number;
  num_retries?: number;
  restart_delay?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettings {
  hls_akamai_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsAkamaiSettings;
  hls_basic_put_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsBasicPutSettings;
  hls_media_store_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsMediaStoreSettings;
  hls_s3_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsS3Settings;
  hls_webdav_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettingsHlsWebdavSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsKeyProviderSettingsStaticKeySettingsKeyProviderServer {
  uri: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsKeyProviderSettingsStaticKeySettings {
  static_key_value: string;
  key_provider_server?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsKeyProviderSettingsStaticKeySettingsKeyProviderServer;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsKeyProviderSettings {
  static_key_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsKeyProviderSettingsStaticKeySettings[];
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettings {
  caption_language_mappings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsCaptionLanguageMappings[];
  destination: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsDestination;
  hls_cdn_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsHlsCdnSettings[];
  key_provider_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettingsKeyProviderSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMediaPackageGroupSettingsDestination {
  destination_ref_id: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMediaPackageGroupSettings {
  destination: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMediaPackageGroupSettingsDestination;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMsSmoothGroupSettingsDestination {
  destination_ref_id: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMsSmoothGroupSettings {
  filecache_duration?: number;
  num_retries?: number;
  restart_delay?: number;
  destination: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMsSmoothGroupSettingsDestination;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMultiplexGroupSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsRtmpGroupSettings {
  ad_markers?: string[];
  restart_delay?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsUdpGroupSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettings {
  archive_group_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsArchiveGroupSettings[];
  frame_capture_group_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsFrameCaptureGroupSettings;
  hls_group_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsHlsGroupSettings;
  media_package_group_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMediaPackageGroupSettings;
  ms_smooth_group_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMsSmoothGroupSettings;
  multiplex_group_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsMultiplexGroupSettings;
  rtmp_group_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsRtmpGroupSettings;
  udp_group_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettingsUdpGroupSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsM2tsSettingsDvbNitSettings {
  network_id: number;
  network_name: string;
  rep_interval?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsM2tsSettingsDvbSdtSettings {
  output_sdt?: string;
  rep_interval?: number;
  service_name?: string;
  service_provider_name?: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsM2tsSettingsDvbTdtSettings {
  rep_interval?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsM2tsSettings {
  arib?: string;
  arib_captions_pid_control?: string;
  audio_buffer_model?: string;
  audio_frames_per_pes?: number;
  audio_stream_type?: string;
  bitrate?: number;
  buffer_model?: string;
  cc_descriptor?: string;
  ebif?: string;
  ebp_audio_interval?: string;
  ebp_lookahead_ms?: number;
  ebp_placement?: string;
  ecm_pid?: string;
  es_rate_in_pes?: string;
  fragment_time?: number;
  klv?: string;
  nielsen_id3_behavior?: string;
  null_packet_bitrate?: number;
  pat_interval?: number;
  pcr_control?: string;
  pcr_period?: number;
  pcr_pid?: string;
  pmt_interval?: number;
  program_num?: number;
  rate_mode?: string;
  scte35_control?: string;
  segmentation_markers?: string;
  segmentation_style?: string;
  segmentation_time?: number;
  timed_metadata_behavior?: string;
  transport_stream_id?: number;
  dvb_nit_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsM2tsSettingsDvbNitSettings;
  dvb_sdt_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsM2tsSettingsDvbSdtSettings;
  dvb_tdt_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsM2tsSettingsDvbTdtSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsRawSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettings {
  m2ts_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsM2tsSettings;
  raw_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettingsRawSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettings {
  extension?: string;
  name_modifier?: string;
  container_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettingsContainerSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsFrameCaptureOutputSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsAudioOnlyHlsSettingsAudioOnlyImage {
  uri: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsAudioOnlyHlsSettings {
  audio_only_image?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsAudioOnlyHlsSettingsAudioOnlyImage;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsFmp4HlsSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsFrameCaptureHlsSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsStandardHlsSettingsM3u8Settings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsStandardHlsSettings {
  m3u8_settings: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsStandardHlsSettingsM3u8Settings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettings {
  audio_only_hls_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsAudioOnlyHlsSettings;
  fmp4_hls_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsFmp4HlsSettings;
  frame_capture_hls_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsFrameCaptureHlsSettings;
  standard_hls_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettingsStandardHlsSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettings {
  hls_settings: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettingsHlsSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsMediaPackageOutputSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsMsSmoothOutputSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsMultiplexOutputSettingsDestination {
  destination_ref_id: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsMultiplexOutputSettings {
  destination: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsMultiplexOutputSettingsDestination;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsRtmpOutputSettingsDestination {
  destination_ref_id: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsRtmpOutputSettings {
  destination: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsRtmpOutputSettingsDestination;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettingsM2tsSettingsDvbNitSettings {
  network_id: number;
  network_name: string;
  rep_interval?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettingsM2tsSettingsDvbSdtSettings {
  output_sdt?: string;
  rep_interval?: number;
  service_name?: string;
  service_provider_name?: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettingsM2tsSettingsDvbTdtSettings {
  rep_interval?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettingsM2tsSettings {
  arib?: string;
  arib_captions_pid_control?: string;
  audio_buffer_model?: string;
  audio_frames_per_pes?: number;
  audio_stream_type?: string;
  bitrate?: number;
  buffer_model?: string;
  cc_descriptor?: string;
  ebif?: string;
  ebp_audio_interval?: string;
  ebp_lookahead_ms?: number;
  ebp_placement?: string;
  ecm_pid?: string;
  es_rate_in_pes?: string;
  fragment_time?: number;
  klv?: string;
  nielsen_id3_behavior?: string;
  null_packet_bitrate?: number;
  pat_interval?: number;
  pcr_control?: string;
  pcr_period?: number;
  pcr_pid?: string;
  pmt_interval?: number;
  program_num?: number;
  rate_mode?: string;
  scte35_control?: string;
  segmentation_markers?: string;
  segmentation_style?: string;
  segmentation_time?: number;
  timed_metadata_behavior?: string;
  transport_stream_id?: number;
  dvb_nit_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettingsM2tsSettingsDvbNitSettings;
  dvb_sdt_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettingsM2tsSettingsDvbSdtSettings;
  dvb_tdt_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettingsM2tsSettingsDvbTdtSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettings {
  m2ts_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettingsM2tsSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsDestination {
  destination_ref_id: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsFecOutputSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettings {
  container_settings: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsContainerSettings;
  destination: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsDestination;
  fec_output_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettingsFecOutputSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettings {
  archive_output_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsArchiveOutputSettings;
  frame_capture_output_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsFrameCaptureOutputSettings;
  hls_output_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsHlsOutputSettings;
  media_package_output_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsMediaPackageOutputSettings;
  ms_smooth_output_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsMsSmoothOutputSettings;
  multiplex_output_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsMultiplexOutputSettings;
  rtmp_output_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsRtmpOutputSettings;
  udp_output_settings?: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettingsUdpOutputSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputs {
  audio_description_names?: string[];
  output_name?: string;
  video_description_name?: string;
  output_settings: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputsOutputSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsOutputGroups {
  name?: string;
  output_group_settings: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputGroupSettings;
  outputs: AwsMedialiveChannelArgsEncoderSettingsOutputGroupsOutputs[];
}

export interface AwsMedialiveChannelArgsEncoderSettingsTimecodeConfig {
  source: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsFrameCaptureSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH264SettingsFilterSettingsTemporalFilterSettings {
  post_filter_sharpening?: string;
  strength?: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH264SettingsFilterSettings {
  temporal_filter_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH264SettingsFilterSettingsTemporalFilterSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH264Settings {
  filter_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH264SettingsFilterSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsColorSpacePassthroughSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsDolbyVision81Settings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsHdr10Settings {
  max_cll?: number;
  max_fall?: number;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsRec601Settings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsRec709Settings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettings {
  color_space_passthrough_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsColorSpacePassthroughSettings;
  dolby_vision81_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsDolbyVision81Settings;
  hdr10_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsHdr10Settings;
  rec601_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsRec601Settings;
  rec709_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettingsRec709Settings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsFilterSettingsTemporalFilterSettings {
  post_filter_sharpening?: string;
  strength?: string;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsFilterSettings {
  temporal_filter_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsFilterSettingsTemporalFilterSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsTimecodeBurninSettings {
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265Settings {
  bitrate: number;
  buf_size?: number;
  framerate_denominator: number;
  framerate_numerator: number;
  gop_closed_cadence?: number;
  gop_size?: number;
  max_bitrate?: number;
  min_i_interval?: number;
  min_qp?: number;
  par_denominator?: number;
  par_numerator?: number;
  qvbr_quality_level?: number;
  slices?: number;
  tile_height?: number;
  tile_width?: number;
  color_space_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsColorSpaceSettings;
  filter_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsFilterSettings;
  timecode_burnin_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265SettingsTimecodeBurninSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettings {
  frame_capture_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsFrameCaptureSettings;
  h264_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH264Settings;
  h265_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettingsH265Settings;
}

export interface AwsMedialiveChannelArgsEncoderSettingsVideoDescriptions {
  name: string;
  codec_settings?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptionsCodecSettings;
}

export interface AwsMedialiveChannelArgsEncoderSettings {
  audio_descriptions?: AwsMedialiveChannelArgsEncoderSettingsAudioDescriptions[];
  avail_blanking?: AwsMedialiveChannelArgsEncoderSettingsAvailBlanking;
  caption_descriptions?: AwsMedialiveChannelArgsEncoderSettingsCaptionDescriptions[];
  global_configuration?: AwsMedialiveChannelArgsEncoderSettingsGlobalConfiguration;
  motion_graphics_configuration?: AwsMedialiveChannelArgsEncoderSettingsMotionGraphicsConfiguration;
  nielsen_configuration?: AwsMedialiveChannelArgsEncoderSettingsNielsenConfiguration;
  output_groups: AwsMedialiveChannelArgsEncoderSettingsOutputGroups[];
  timecode_config: AwsMedialiveChannelArgsEncoderSettingsTimecodeConfig;
  video_descriptions?: AwsMedialiveChannelArgsEncoderSettingsVideoDescriptions[];
}

export interface AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverConditionFailoverConditionSettingsAudioSilenceSettings {
  audio_selector_name: string;
  audio_silence_threshold_msec?: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverConditionFailoverConditionSettingsInputLossSettings {
  input_loss_threshold_msec?: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverConditionFailoverConditionSettingsVideoBlackSettings {
  black_detect_threshold?: number;
  video_black_threshold_msec?: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverConditionFailoverConditionSettings {
  audio_silence_settings?: AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverConditionFailoverConditionSettingsAudioSilenceSettings;
  input_loss_settings?: AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverConditionFailoverConditionSettingsInputLossSettings;
  video_black_settings?: AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverConditionFailoverConditionSettingsVideoBlackSettings;
}

export interface AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverCondition {
  failover_condition_settings?: AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverConditionFailoverConditionSettings;
}

export interface AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettings {
  error_clear_time_msec?: number;
  input_preference?: string;
  secondary_input_id: string;
  failover_condition?: AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettingsFailoverCondition[];
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioHlsRenditionSelection {
  group_id: string;
  name: string;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioLanguageSelection {
  language_code: string;
  language_selection_policy?: string;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioPidSelection {
  pid: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioTrackSelectionDolbyEDecode {
  program_selection: string;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioTrackSelectionTracks {
  track: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioTrackSelection {
  dolby_e_decode?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioTrackSelectionDolbyEDecode;
  tracks: AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioTrackSelectionTracks[];
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettings {
  audio_hls_rendition_selection?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioHlsRenditionSelection;
  audio_language_selection?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioLanguageSelection;
  audio_pid_selection?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioPidSelection;
  audio_track_selection?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettingsAudioTrackSelection;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelector {
  name: string;
  selector_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelectorSelectorSettings;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsAncillarySourceSettings {
  source_ancillary_channel_number?: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsAribSourceSettings {
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsDvbSubSourceSettings {
  ocr_language?: string;
  pid?: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsEmbeddedSourceSettings {
  convert_608_to_708?: string;
  scte20_detection?: string;
  source_608_channel_number?: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsScte20SourceSettings {
  convert_608_to_708?: string;
  source_608_channel_number?: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsScte27SourceSettings {
  ocr_language?: string;
  pid?: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsTeletextSourceSettingsOutputRectangle {
  height: number;
  left_offset: number;
  top_offset: number;
  width: number;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsTeletextSourceSettings {
  page_number?: string;
  output_rectangle?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsTeletextSourceSettingsOutputRectangle;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettings {
  ancillary_source_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsAncillarySourceSettings;
  arib_source_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsAribSourceSettings;
  dvb_sub_source_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsDvbSubSourceSettings;
  embedded_source_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsEmbeddedSourceSettings;
  scte20_source_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsScte20SourceSettings;
  scte27_source_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsScte27SourceSettings;
  teletext_source_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettingsTeletextSourceSettings;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelector {
  language_code?: string;
  name: string;
  selector_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelectorSelectorSettings;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsNetworkInputSettingsHlsInputSettings {
  bandwidth?: number;
  buffer_segments?: number;
  retries?: number;
  retry_interval?: number;
  scte35_source?: string;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsNetworkInputSettings {
  server_validation?: string;
  hls_input_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsNetworkInputSettingsHlsInputSettings;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettingsVideoSelector {
  color_space?: string;
  color_space_usage?: string;
}

export interface AwsMedialiveChannelArgsInputAttachmentsInputSettings {
  deblock_filter?: string;
  denoise_filter?: string;
  filter_strength?: number;
  scte35_pid?: number;
  smpte2038_data_preference?: string;
  source_end_behavior?: string;
  audio_selector?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsAudioSelector[];
  caption_selector?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsCaptionSelector[];
  network_input_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsNetworkInputSettings;
  video_selector?: AwsMedialiveChannelArgsInputAttachmentsInputSettingsVideoSelector;
}

export interface AwsMedialiveChannelArgsInputAttachments {
  input_attachment_name: string;
  input_id: string;
  automatic_input_failover_settings?: AwsMedialiveChannelArgsInputAttachmentsAutomaticInputFailoverSettings;
  input_settings?: AwsMedialiveChannelArgsInputAttachmentsInputSettings;
}

export interface AwsMedialiveChannelArgsInputSpecification {
  codec: string;
  input_resolution: string;
  maximum_bitrate: string;
}

export interface AwsMedialiveChannelArgsMaintenance {
  maintenance_day: string;
  maintenance_start_time: string;
}

export interface AwsMedialiveChannelArgsTimeouts {
  create?: string;
  delete?: string;
  update?: string;
}

export interface AwsMedialiveChannelArgsVpc {
  public_address_allocation_ids: string[];
  subnet_ids: string[];
}

export interface AwsMedialiveChannelArgs {
  channel_class: string;
  name: string;
  role_arn?: string;
  start_channel?: boolean;
  tags?: { [key: string]: string };
  cdi_input_specification?: AwsMedialiveChannelArgsCdiInputSpecification;
  destinations: AwsMedialiveChannelArgsDestinations[];
  encoder_settings: AwsMedialiveChannelArgsEncoderSettings;
  input_attachments: AwsMedialiveChannelArgsInputAttachments[];
  input_specification: AwsMedialiveChannelArgsInputSpecification;
  maintenance?: AwsMedialiveChannelArgsMaintenance;
  timeouts?: AwsMedialiveChannelArgsTimeouts;
  vpc?: AwsMedialiveChannelArgsVpc;
}

export class aws_medialive_channel extends TerraformResource {
  constructor(protected readonly terraformConfig: TerraformConfig, protected readonly resourceName: string, readonly args: AwsMedialiveChannelArgs) {
    const meta = {cdi_input_specification:{isBlock:true},destinations:{isBlock:true,media_package_settings:{isBlock:true},multiplex_settings:{isBlock:true},settings:{isBlock:true}},encoder_settings:{isBlock:true,audio_descriptions:{isBlock:true,audio_normalization_settings:{isBlock:true},audio_watermark_settings:{isBlock:true,nielsen_watermarks_settings:{isBlock:true,nielsen_cbet_settings:{isBlock:true},nielsen_naes_ii_nw_settings:{isBlock:true}}},codec_settings:{isBlock:true,aac_settings:{isBlock:true},ac3_settings:{isBlock:true},eac3_atmos_settings:{isBlock:true},eac3_settings:{isBlock:true},mp2_settings:{isBlock:true},pass_through_settings:{isBlock:true},wav_settings:{isBlock:true}},remix_settings:{isBlock:true,channel_mappings:{isBlock:true,input_channel_levels:{isBlock:true}}}},avail_blanking:{isBlock:true,avail_blanking_image:{isBlock:true}},caption_descriptions:{isBlock:true,destination_settings:{isBlock:true,arib_destination_settings:{isBlock:true},burn_in_destination_settings:{isBlock:true,font:{isBlock:true}},dvb_sub_destination_settings:{isBlock:true,font:{isBlock:true}},ebu_tt_d_destination_settings:{isBlock:true},embedded_destination_settings:{isBlock:true},embedded_plus_scte20_destination_settings:{isBlock:true},rtmp_caption_info_destination_settings:{isBlock:true},scte20_plus_embedded_destination_settings:{isBlock:true},scte27_destination_settings:{isBlock:true},smpte_tt_destination_settings:{isBlock:true},teletext_destination_settings:{isBlock:true},ttml_destination_settings:{isBlock:true},webvtt_destination_settings:{isBlock:true}}},global_configuration:{isBlock:true,input_loss_behavior:{isBlock:true,input_loss_image_slate:{isBlock:true}}},motion_graphics_configuration:{isBlock:true,motion_graphics_settings:{isBlock:true,html_motion_graphics_settings:{isBlock:true}}},nielsen_configuration:{isBlock:true},output_groups:{isBlock:true,output_group_settings:{isBlock:true,archive_group_settings:{isBlock:true,archive_cdn_settings:{isBlock:true,archive_s3_settings:{isBlock:true}},destination:{isBlock:true}},frame_capture_group_settings:{isBlock:true,destination:{isBlock:true},frame_capture_cdn_settings:{isBlock:true,frame_capture_s3_settings:{isBlock:true}}},hls_group_settings:{isBlock:true,caption_language_mappings:{isBlock:true},destination:{isBlock:true},hls_cdn_settings:{isBlock:true,hls_akamai_settings:{isBlock:true},hls_basic_put_settings:{isBlock:true},hls_media_store_settings:{isBlock:true},hls_s3_settings:{isBlock:true},hls_webdav_settings:{isBlock:true}},key_provider_settings:{isBlock:true,static_key_settings:{isBlock:true,key_provider_server:{isBlock:true}}}},media_package_group_settings:{isBlock:true,destination:{isBlock:true}},ms_smooth_group_settings:{isBlock:true,destination:{isBlock:true}},multiplex_group_settings:{isBlock:true},rtmp_group_settings:{isBlock:true},udp_group_settings:{isBlock:true}},outputs:{isBlock:true,output_settings:{isBlock:true,archive_output_settings:{isBlock:true,container_settings:{isBlock:true,m2ts_settings:{isBlock:true,dvb_nit_settings:{isBlock:true},dvb_sdt_settings:{isBlock:true},dvb_tdt_settings:{isBlock:true}},raw_settings:{isBlock:true}}},frame_capture_output_settings:{isBlock:true},hls_output_settings:{isBlock:true,hls_settings:{isBlock:true,audio_only_hls_settings:{isBlock:true,audio_only_image:{isBlock:true}},fmp4_hls_settings:{isBlock:true},frame_capture_hls_settings:{isBlock:true},standard_hls_settings:{isBlock:true,m3u8_settings:{isBlock:true}}}},media_package_output_settings:{isBlock:true},ms_smooth_output_settings:{isBlock:true},multiplex_output_settings:{isBlock:true,destination:{isBlock:true}},rtmp_output_settings:{isBlock:true,destination:{isBlock:true}},udp_output_settings:{isBlock:true,container_settings:{isBlock:true,m2ts_settings:{isBlock:true,dvb_nit_settings:{isBlock:true},dvb_sdt_settings:{isBlock:true},dvb_tdt_settings:{isBlock:true}}},destination:{isBlock:true},fec_output_settings:{isBlock:true}}}}},timecode_config:{isBlock:true},video_descriptions:{isBlock:true,codec_settings:{isBlock:true,frame_capture_settings:{isBlock:true},h264_settings:{isBlock:true,filter_settings:{isBlock:true,temporal_filter_settings:{isBlock:true}}},h265_settings:{isBlock:true,color_space_settings:{isBlock:true,color_space_passthrough_settings:{isBlock:true},dolby_vision81_settings:{isBlock:true},hdr10_settings:{isBlock:true},rec601_settings:{isBlock:true},rec709_settings:{isBlock:true}},filter_settings:{isBlock:true,temporal_filter_settings:{isBlock:true}},timecode_burnin_settings:{isBlock:true}}}}},input_attachments:{isBlock:true,automatic_input_failover_settings:{isBlock:true,failover_condition:{isBlock:true,failover_condition_settings:{isBlock:true,audio_silence_settings:{isBlock:true},input_loss_settings:{isBlock:true},video_black_settings:{isBlock:true}}}},input_settings:{isBlock:true,audio_selector:{isBlock:true,selector_settings:{isBlock:true,audio_hls_rendition_selection:{isBlock:true},audio_language_selection:{isBlock:true},audio_pid_selection:{isBlock:true},audio_track_selection:{isBlock:true,dolby_e_decode:{isBlock:true},tracks:{isBlock:true}}}},caption_selector:{isBlock:true,selector_settings:{isBlock:true,ancillary_source_settings:{isBlock:true},arib_source_settings:{isBlock:true},dvb_sub_source_settings:{isBlock:true},embedded_source_settings:{isBlock:true},scte20_source_settings:{isBlock:true},scte27_source_settings:{isBlock:true},teletext_source_settings:{isBlock:true,output_rectangle:{isBlock:true}}}},network_input_settings:{isBlock:true,hls_input_settings:{isBlock:true}},video_selector:{isBlock:true}}},input_specification:{isBlock:true},maintenance:{isBlock:true},timeouts:{isBlock:true},vpc:{isBlock:true}};
    super(terraformConfig, "resource", args, meta, "aws_medialive_channel", resourceName);
  }

  get arn(): string {
    return `${this.resourceType}.${this.resourceName}.arn`;
  }

  get channel_class(): string {
    return `${this.resourceType}.${this.resourceName}.channel_class`;
  }

  get channel_id(): string {
    return `${this.resourceType}.${this.resourceName}.channel_id`;
  }

  get id(): string {
    return `${this.resourceType}.${this.resourceName}.id`;
  }

  get log_level(): string {
    return `${this.resourceType}.${this.resourceName}.log_level`;
  }

  get name(): string {
    return `${this.resourceType}.${this.resourceName}.name`;
  }

  get tags_all(): string {
    return `${this.resourceType}.${this.resourceName}.tags_all`;
  }
}
