import { TerraformConfig, TerraformResource } from "@tfkonf/core";

export interface AwsLexv2modelsSlotArgsMultipleValuesSetting {
  allow_multiple_values?: boolean;
}

export interface AwsLexv2modelsSlotArgsObfuscationSetting {
  obfuscation_setting_type: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecificationDefaultValueList {
  default_value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecification {
  default_value_list?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecificationDefaultValueList[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessageCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessageImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessageImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessagePlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessageSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessage {
  custom_payload?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessageCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessageImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessagePlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessageSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationPlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariation {
  custom_payload?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationPlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariationSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroup {
  message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupMessage[];
  variation?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroupVariation[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAllowedInputTypes {
  allow_audio_input: boolean;
  allow_dtmf_input: boolean;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationAudioSpecification {
  end_timeout_ms: number;
  max_length_ms: number;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationDtmfSpecification {
  deletion_character: string;
  end_character: string;
  end_timeout_ms: number;
  max_length: number;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecification {
  start_timeout_ms: number;
  audio_specification?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationAudioSpecification[];
  dtmf_specification?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationDtmfSpecification[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationTextInputSpecification {
  start_timeout_ms: number;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecification {
  allow_interrupt?: boolean;
  map_block_key: string;
  allowed_input_types?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAllowedInputTypes[];
  audio_and_dtmf_input_specification?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecification[];
  text_input_specification?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationTextInputSpecification[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecification {
  allow_interrupt?: boolean;
  max_retries: number;
  message_selection_strategy?: string;
  message_group?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationMessageGroup[];
  prompt_attempts_specification?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecificationPromptAttemptsSpecification[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingSampleUtterance {
  utterance: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessagePlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessage {
  custom_payload?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessagePlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationPlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariation {
  custom_payload?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationPlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroup {
  message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessage[];
  variation?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariation[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponse {
  allow_interrupt?: boolean;
  message_group?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroup[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessagePlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessage {
  custom_payload?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessagePlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationPlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariation {
  custom_payload?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationPlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroup {
  message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessage[];
  variation?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariation[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponse {
  allow_interrupt?: boolean;
  frequency_in_seconds: number;
  timeout_in_seconds: number;
  message_group?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroup[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessagePlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessage {
  custom_payload?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessagePlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationPlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariation {
  custom_payload?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationPlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroup {
  message?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessage[];
  variation?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariation[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponse {
  allow_interrupt?: boolean;
  message_group?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroup[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecification {
  active?: boolean;
  continue_response?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationContinueResponse[];
  still_waiting_response?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponse[];
  waiting_response?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecificationWaitingResponse[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSetting {
  default_value_specification?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingDefaultValueSpecification[];
  prompt_specification?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingPromptSpecification[];
  sample_utterance?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingSampleUtterance[];
  wait_and_continue_specification?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSettingWaitAndContinueSpecification[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecification {
  map_block_key: string;
  slot_type_id: string;
  value_elicitation_setting?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecificationValueElicitationSetting[];
}

export interface AwsLexv2modelsSlotArgsSubSlotSetting {
  expression?: string;
  slot_specification?: AwsLexv2modelsSlotArgsSubSlotSettingSlotSpecification[];
}

export interface AwsLexv2modelsSlotArgsTimeouts {
  create?: string;
  delete?: string;
  update?: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingDefaultValueSpecificationDefaultValueList {
  default_value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingDefaultValueSpecification {
  default_value_list?: AwsLexv2modelsSlotArgsValueElicitationSettingDefaultValueSpecificationDefaultValueList[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessageCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessageImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessageImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessagePlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessageSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessage {
  custom_payload?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessageCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessageImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessagePlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessageSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationPlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariation {
  custom_payload?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationPlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariationSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroup {
  message?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupMessage[];
  variation?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroupVariation[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAllowedInputTypes {
  allow_audio_input: boolean;
  allow_dtmf_input: boolean;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationAudioSpecification {
  end_timeout_ms: number;
  max_length_ms: number;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationDtmfSpecification {
  deletion_character: string;
  end_character: string;
  end_timeout_ms: number;
  max_length: number;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecification {
  start_timeout_ms: number;
  audio_specification?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationAudioSpecification[];
  dtmf_specification?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecificationDtmfSpecification[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationTextInputSpecification {
  start_timeout_ms: number;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecification {
  allow_interrupt?: boolean;
  map_block_key: string;
  allowed_input_types?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAllowedInputTypes[];
  audio_and_dtmf_input_specification?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationAudioAndDtmfInputSpecification[];
  text_input_specification?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecificationTextInputSpecification[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecification {
  allow_interrupt?: boolean;
  max_retries: number;
  message_selection_strategy?: string;
  message_group?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationMessageGroup[];
  prompt_attempts_specification?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecificationPromptAttemptsSpecification[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingSampleUtterance {
  utterance: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingSlotResolutionSetting {
  slot_resolution_strategy: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessagePlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessage {
  custom_payload?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessagePlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessageSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationPlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariation {
  custom_payload?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationPlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariationSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroup {
  message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupMessage[];
  variation?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroupVariation[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponse {
  allow_interrupt?: boolean;
  message_group?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponseMessageGroup[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessagePlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessage {
  custom_payload?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessagePlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessageSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationPlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariation {
  custom_payload?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationPlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariationSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroup {
  message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupMessage[];
  variation?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroupVariation[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponse {
  allow_interrupt?: boolean;
  frequency_in_seconds: number;
  timeout_in_seconds: number;
  message_group?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponseMessageGroup[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessagePlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessage {
  custom_payload?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessagePlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessageSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationCustomPayload {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationImageResponseCardButton {
  text: string;
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationImageResponseCard {
  image_url?: string;
  subtitle?: string;
  title: string;
  button?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationImageResponseCardButton[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationPlainTextMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationSsmlMessage {
  value: string;
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariation {
  custom_payload?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationCustomPayload[];
  image_response_card?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationImageResponseCard[];
  plain_text_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationPlainTextMessage[];
  ssml_message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariationSsmlMessage[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroup {
  message?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupMessage[];
  variation?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroupVariation[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponse {
  allow_interrupt?: boolean;
  message_group?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponseMessageGroup[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecification {
  active?: boolean;
  continue_response?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationContinueResponse[];
  still_waiting_response?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationStillWaitingResponse[];
  waiting_response?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecificationWaitingResponse[];
}

export interface AwsLexv2modelsSlotArgsValueElicitationSetting {
  slot_constraint: string;
  default_value_specification?: AwsLexv2modelsSlotArgsValueElicitationSettingDefaultValueSpecification[];
  prompt_specification?: AwsLexv2modelsSlotArgsValueElicitationSettingPromptSpecification[];
  sample_utterance?: AwsLexv2modelsSlotArgsValueElicitationSettingSampleUtterance[];
  slot_resolution_setting?: AwsLexv2modelsSlotArgsValueElicitationSettingSlotResolutionSetting[];
  wait_and_continue_specification?: AwsLexv2modelsSlotArgsValueElicitationSettingWaitAndContinueSpecification[];
}

export interface AwsLexv2modelsSlotArgs {
  bot_id: string;
  bot_version: string;
  description?: string;
  intent_id: string;
  locale_id: string;
  name: string;
  multiple_values_setting?: AwsLexv2modelsSlotArgsMultipleValuesSetting[];
  obfuscation_setting?: AwsLexv2modelsSlotArgsObfuscationSetting[];
  sub_slot_setting?: AwsLexv2modelsSlotArgsSubSlotSetting[];
  timeouts?: AwsLexv2modelsSlotArgsTimeouts;
  value_elicitation_setting?: AwsLexv2modelsSlotArgsValueElicitationSetting[];
}

export class aws_lexv2models_slot extends TerraformResource {
  constructor(protected readonly terraformConfig: TerraformConfig, protected readonly resourceName: string, readonly args: AwsLexv2modelsSlotArgs) {
    const meta = {multiple_values_setting:{isBlock:true},obfuscation_setting:{isBlock:true},sub_slot_setting:{isBlock:true,slot_specification:{isBlock:true,value_elicitation_setting:{isBlock:true,default_value_specification:{isBlock:true,default_value_list:{isBlock:true}},prompt_specification:{isBlock:true,message_group:{isBlock:true,message:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}},variation:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}}},prompt_attempts_specification:{isBlock:true,allowed_input_types:{isBlock:true},audio_and_dtmf_input_specification:{isBlock:true,audio_specification:{isBlock:true},dtmf_specification:{isBlock:true}},text_input_specification:{isBlock:true}}},sample_utterance:{isBlock:true},wait_and_continue_specification:{isBlock:true,continue_response:{isBlock:true,message_group:{isBlock:true,message:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}},variation:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}}}},still_waiting_response:{isBlock:true,message_group:{isBlock:true,message:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}},variation:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}}}},waiting_response:{isBlock:true,message_group:{isBlock:true,message:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}},variation:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}}}}}}}},timeouts:{isBlock:true},value_elicitation_setting:{isBlock:true,default_value_specification:{isBlock:true,default_value_list:{isBlock:true}},prompt_specification:{isBlock:true,message_group:{isBlock:true,message:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}},variation:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}}},prompt_attempts_specification:{isBlock:true,allowed_input_types:{isBlock:true},audio_and_dtmf_input_specification:{isBlock:true,audio_specification:{isBlock:true},dtmf_specification:{isBlock:true}},text_input_specification:{isBlock:true}}},sample_utterance:{isBlock:true},slot_resolution_setting:{isBlock:true},wait_and_continue_specification:{isBlock:true,continue_response:{isBlock:true,message_group:{isBlock:true,message:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}},variation:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}}}},still_waiting_response:{isBlock:true,message_group:{isBlock:true,message:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}},variation:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}}}},waiting_response:{isBlock:true,message_group:{isBlock:true,message:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}},variation:{isBlock:true,custom_payload:{isBlock:true},image_response_card:{isBlock:true,button:{isBlock:true}},plain_text_message:{isBlock:true},ssml_message:{isBlock:true}}}}}}};
    super(terraformConfig, "resource", args, meta, "aws_lexv2models_slot", resourceName);
  }

  get bot_id(): string {
    return `${this.resourceType}.${this.resourceName}.bot_id`;
  }

  get bot_version(): string {
    return `${this.resourceType}.${this.resourceName}.bot_version`;
  }

  get id(): string {
    return `${this.resourceType}.${this.resourceName}.id`;
  }

  get intent_id(): string {
    return `${this.resourceType}.${this.resourceName}.intent_id`;
  }

  get locale_id(): string {
    return `${this.resourceType}.${this.resourceName}.locale_id`;
  }

  get name(): string {
    return `${this.resourceType}.${this.resourceName}.name`;
  }

  get slot_id(): string {
    return `${this.resourceType}.${this.resourceName}.slot_id`;
  }

  get slot_type_id(): string {
    return `${this.resourceType}.${this.resourceName}.slot_type_id`;
  }
}
